services:
  - type: web
    name: devportfolio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn devportfolio.wsgi"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
